# Generated by Django 3.1.6 on 2021-06-26 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Determines if user can access the admin site', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('max_points', models.IntegerField(blank=True, null=True)),
                ('user_point', models.IntegerField(blank=True, null=True)),
                ('date_due', models.DateTimeField(verbose_name='date due')),
                ('description', models.TextField(blank=True)),
                ('assignment_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('name', models.CharField(max_length=50)),
                ('imageFile', models.ImageField(upload_to='lectures')),
                ('lecture_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('list_assignments', models.ManyToManyField(blank=True, to='myapi.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('course_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('list_lectures', models.ManyToManyField(blank=True, to='myapi.Lecture')),
                ('list_students', models.ManyToManyField(blank=True, to='myapi.Student')),
            ],
        ),
    ]
