# Generated by Django 3.1.6 on 2021-06-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('max_points', models.IntegerField(blank=True, null=True)),
                ('user_point', models.IntegerField(blank=True, null=True)),
                ('date_due', models.DateTimeField(verbose_name='date due')),
                ('description', models.TextField(blank=True)),
                ('assignment_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('name', models.CharField(max_length=50)),
                ('imageFile', models.ImageField(upload_to='lectures')),
                ('lecture_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('list_assignments', models.ManyToManyField(blank=True, to='myapi.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('course_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('list_lectures', models.ManyToManyField(blank=True, to='myapi.Lecture')),
                ('list_students', models.ManyToManyField(blank=True, to='myapi.Student')),
            ],
        ),
    ]
