# Generated by Django 3.1.6 on 2021-06-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_assignment_course_lecture_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
